# Generated by Django 2.1.7 on 2019-03-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_auto_20190307_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='porttemplate',
            unique_together=set(),
        ),
    ]
