# Generated by Django 2.2.10 on 2020-02-12 06:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_custom_tag_models'),
        ('dcim', '0090_cable_termination_models'),
        ('extras', '0037_auto_20200212_0648'),
        ('ipam', '0033_deterministic_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortTemplateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='port_template_groups', to='dcim.Site')),
            ],
            options={
                'verbose_name': 'Port-templates group',
                'verbose_name_plural': 'Port-templates groups',
                'ordering': ['site', 'name'],
                'unique_together': {('site', 'name'), ('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PortTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('vid', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(default='active', max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PortTemplates', to='ipam.PortTemplateGroup')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PortTemplates', to='ipam.Role')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PortTemplates', to='dcim.Site')),
                ('tagged_vlans', models.ManyToManyField(blank=True, related_name='roles_as_tagged', to='ipam.VLAN')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PortTemplates', to='tenancy.Tenant')),
                ('untagged_vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_as_untagged', to='ipam.VLAN')),
            ],
            options={
                'verbose_name': 'Port-template',
                'verbose_name_plural': 'Port-templates',
                'ordering': ['site', 'group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='prefix',
            name='port_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefixes', to='ipam.PortTemplate'),
        ),
    ]
