# Generated by Django 2.2.10 on 2020-02-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0034_auto_20200212_0648'),
        ('dcim', '0090_cable_termination_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port_template_groups',
            field=models.ManyToManyField(blank=True, related_name='device_port_template_group', to='ipam.PortTemplateGroup'),
        ),
        migrations.AddField(
            model_name='interface',
            name='port_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PortTemplate', to='ipam.PortTemplate'),
        ),
        migrations.AddField(
            model_name='platform',
            name='end_of_life',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='platform',
            name='end_of_sale',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='platform',
            name='end_of_support',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='platform',
            name='is_last_standard',
            field=models.BooleanField(default=False),
        ),
    ]
